data_root: data/bike

data_ingestion:
  root_dir: data/bike/data_ingestion
  download_url: https://raw.githubusercontent.com/Vicky7873/data/refs/heads/main/Used_Bikes.csv
  bike_raw_data: data/bike/data_ingestion/used_bikes.csv

feature_engeenering:
  root_dir: data/bike/feature_engeenering
  bike_raw_data: data/bike/data_ingestion/used_bikes.csv
  feature_eng_data: data/bike/feature_engeenering/clean_bike.csv

splliting_data:
  root_dir: data/bike/data_split
  feature_eng_data: data/bike/feature_engeenering/clean_bike.csv
  X_train: data/bike/data_split/X_train.csv
  X_test: data/bike/data_split/X_test.csv
  y_train: data/bike/data_split/y_train.csv
  y_test: data/bike/data_split/y_test.csv

hyper_tune:
  root_dir: data/bike/bike_tune
  X_train: data/bike/data_split/X_train.csv
  X_test: data/bike/data_split/X_test.csv
  y_train: data/bike/data_split/y_train.csv
  y_test: data/bike/data_split/y_test.csv
  tunned_model: data/bike/bike_tune/tunned_model.pkl


model_training:
  root_dir: data/bike/model_training
  X_train: data/bike/data_split/X_train.csv
  y_train: data/bike/data_split/y_train.csv
  save_model: data/bike/model_training/rfr_pkl
  save_model_for_train: models


model_eval:
  root_dir: data/bike/model_eval
  X_train: data/bike/data_split/X_train.csv
  y_train: data/bike/data_split/y_train.csv
  X_test: data/bike/data_split/X_test.csv
  y_test: data/bike/data_split/y_test.csv
  tunned_model: data/bike/bike_tune/tunned_model.pkl
  score: data/bike/model_eval/score.json

