data_root: data

data_ingestion:
  root_dir: data/car/data_ingestion
  download_uri: "https://raw.githubusercontent.com/Vicky7873/data/refs/heads/main/CAR%20DETAILS%20FROM%20CAR%20DEKHO.csv"
  raw_data_path: data/car/data_ingestion/car.csv

car_fe:
  root_dir: data/car/car_fe
  raw_data_path: data/car/data_ingestion/car.csv
  clean_data: data/car/car_fe/car_clean.csv

car_data_split:
  root_dir: data/car/data_split
  clean_data: data/car/car_fe/car_clean.csv
  X_train: data/car/data_split/X_train.csv
  X_test: data/car/data_split/X_test.csv
  y_train: data/car/data_split/y_train.csv
  y_test: data/car/data_split/y_test.csv

Model_Building:
  root_dir: data/car/Model_training
  X_train: data/car/data_split/X_train.csv
  X_test: data/car/data_split/X_test.csv
  y_train: data/car/data_split/y_train.csv
  y_test: data/car/data_split/y_test.csv
  model_save: data/car/Model_training/best_model.pkl
  model_for_train: models/car_best_model.pkl