data_root: data

data_ingestion:
  root_dir: data/laptop/data_ingestion
  download_url: 'https://raw.githubusercontent.com/Vicky7873/data/main/laptop_price.csv'
  laptop_raw_data: data/laptop/data_ingestion/laptop.csv


feature_eng:
  root_dir: data/laptop/feature_eng
  laptop_raw_data: data/laptop/data_ingestion/laptop.csv
  laptop_cleaned_data: data/laptop/feature_eng/laptop_cleaned.csv


data_split:
  root_dir: data/laptop/data_split
  laptop_cleaned_data: data/laptop/feature_eng/laptop_cleaned.csv
  X_train: data/laptop/data_split/X_train.csv
  X_test: data/laptop/data_split/X_test.csv
  y_train: data/laptop/data_split/y_train.csv
  y_test: data/laptop/data_split/y_test.csv



Model_train:
  root_dir: data/laptop/model_train
  X_train: data/laptop/data_split/X_train.csv
  X_test: data/laptop/data_split/X_test.csv
  y_train: data/laptop/data_split/y_train.csv
  y_test: data/laptop/data_split/y_test.csv
  saved_model: data/laptop/model_train/laptop_model.pkl
  model_for_train: models/laptop_model.pkl


model_eval:
  root_dir: data/laptop/model_eval
  X_train: data/laptop/data_split/X_train.csv
  X_test: data/laptop/data_split/X_test.csv
  y_train: data/laptop/data_split/y_train.csv
  y_test: data/laptop/data_split/y_test.csv
  save_score: data/laptop/model_eval/score.json
  model_for_train: models/laptop_model.pkl
