data_root: data

data_ingestion:
  root_dir: data/laptop/data_ingestion
  download_url: 'https://raw.githubusercontent.com/Vicky7873/data/main/laptop_price.csv'
  laptop_raw_data: data/laptop/data_ingestion/laptop.csv