data_root: data

data_ingestion:
  root_dir: data/mobile/data_ingestion
  download_url: 'https://raw.githubusercontent.com/Vicky7873/data/refs/heads/main/Mobile%20phone%20price.csv'
  mobile_raw_data: data/mobile/data_ingestion/mobile.csv


data_cleaning:
  root_dir: data/mobile/data_cleaning
  mobile_raw_data: data/mobile/data_ingestion/mobile.csv
  mobile_cleaned_data: data/mobile/data_cleaning/mobile_cleaned.csv

feature_eng:
  root_dir: data/mobile/feature_eng
  mobile_cleaned_data: data/mobile/data_cleaning/mobile_cleaned.csv
  final_data: data/mobile/feature_eng/mobile.csv

data_split:
  root_dir: data/mobile/data_split
  X_train: data/mobile/data_split/X_train.csv
  X_test: data/mobile/data_split/X_test.csv
  y_train: data/mobile/data_split/y_train.csv
  y_test: data/mobile/data_split/y_test.csv
  final_data: data/mobile/feature_eng/mobile.csv

model_train:
  root_dir: data/mobile/model_train
  X_train: data/mobile/data_split/X_train.csv
  X_test: data/mobile/data_split/X_test.csv
  y_train: data/mobile/data_split/y_train.csv
  y_test: data/mobile/data_split/y_test.csv
  save_model: data/mobile/model_train/mobile.pkl
  model_for_train: models/mobile.pkl


model_eval:
  root_dir: data/mobile/model_eval
  X_train: data/mobile/data_split/X_train.csv
  X_test: data/mobile/data_split/X_test.csv
  y_train: data/mobile/data_split/y_train.csv
  y_test: data/mobile/data_split/y_test.csv
  save_score: data/mobile/model_eval/score.json
  model_for_train: models/mobile.pkl

